spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5432/tiendauni
  jpa:
    show-sql: true

app:
  cors:
    allowed-origins: "http://localhost:3000, http://localhost:5173, http://localhost:8080"
  aws:
    s3:
      access-key-id: ${AWS_ACCESS_KEY_ID:test}
      secret-access-key: ${AWS_SECRET_ACCESS_KEY:test}
      region: ${AWS_REGION:us-east-1}
      bucket-profile-name: ${AWS_BUCKET_PROFILE_NAME:bucket-profile-dev}
      bucket-publication-name: ${AWS_BUCKET_PUBLICATION_NAME:bucket-publication-dev}
      bucket-profile-url: ${AWS_BUCKET_PROFILE_URL:http://localhost:4566/bucket-profile-dev}
      bucket-publication-url: ${AWS_BUCKET_PUBLICATION_URL:http://localhost:4566/bucket-publication-dev}
  jwt:
    secret: mysecretkey
    expiration: 900 # 15 minutes in seconds
    issuer: TiendaUniAPI
  refresh-token:
    expiration: 604800 # 7 day in seconds
